# Generated by Django 5.2.8 on 2026-03-30 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readingsession',
            name='duration_minutes',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Tiempo leído en minutos (admite decimales, p. ej. 12,5)', max_digits=8),
        ),
    ]
